import {getBackEnd} from "./commons.js";

export const crear_producto_url = getBackEnd() +"producto%2Fcrearproducto";
export const tabla_producto_url = getBackEnd() +"producto%2Flistaproductos";
export const listar_producto_url = getBackEnd() +"producto%2Flistarproductos";
export const estado_producto_url = getBackEnd() +"producto%2Festadoproducto";
export const obtener_producto_url = getBackEnd() +"producto%2Fobtenerproducto";
export const listar_categoria_url = getBackEnd() +"categoria%2Flistarcategorias";
export const crear_persona_url = getBackEnd() +"persona%2Fcrearpersona";
export const tabla_persona_url = getBackEnd() +"persona%2Flistapersonas";
export const obtener_persona_url = getBackEnd() +"persona%2Fobtenerpersona";
export const listar_documento_url = getBackEnd() +"documento%2Flistardocumentos";
export const crear_documento_url= getBackEnd() +"documento%2Fcreardocumento";
export const crear_rol_url = getBackEnd() +"rol%2Fcrearrol";
export const tabla_rol_url = getBackEnd() +"rol%2Flistarol";
export const estado_rol_url = getBackEnd() +"rol%2Festadorol";
export const Obtener_rol_url = getBackEnd() +"rol%2Fobtenerrol";
export const crear_usuario_url = getBackEnd() +"usuario%2Fcrearusuario";
export const tabla_usuario_url = getBackEnd() +"usuario%2Flistausuarios";
export const obtener_usuario_url = getBackEnd() +"usuario%2Fobtenerusuario";
export const login_url = getBackEnd() +"usuario%2Flogin";
export const crear_categoria_url = getBackEnd() +"categoria%2Fcrearcategoria";
export const tabla_categoria_url =getBackEnd() +"categoria%2Flistacategoria";
export const estado_categoria_url =getBackEnd() +"categoria%2Festadocategoria";
export const obtener_categoria_url =getBackEnd() +"categoria%2Fobtenercategoria";
export const  crear_factura_url = getBackEnd() +"factura%2Fcrearfactura"
export const listar_persona_url = getBackEnd() +"persona%2Flistarpersonas";
export const listar_usuario_url = getBackEnd() +"usuario%2Flistarusuario";
export const generar_factura_url = getBackEnd() +"factura%2Fcrearfactura";